# Generated by Django 3.1.2 on 2020-10-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_choice',
            field=models.CharField(choices=[('EVENT1', 'EVENT1) 손가락 인증 이벤트!'), ('EVENT2', 'EVENT2) L.POINT 사용 인증 이벤트!')], default='', max_length=10, null=True),
        ),
    ]
